title: "Organisms/Nav"
description:
  component: "Navigation component"
## Canvas height
height: 150
## Nav alignment settings
alignment:
  description: 'align'
  table:
    category: 'settings'
  default: ''
  options:
    'Default': ''
    'Left': 'left'
    'Center': 'center'
    'Right': 'right'
## Nav Items
items:
  item1:
    title: 'Active'
    in_active_trail: true
    url: '/'
  item2:
    title: 'Link'
    url: '/'
  item3:
    title: 'Dropdown'
    url: '/'
    is_expanded: true
    below:
      item1:
        title: 'Active'
        in_active_trail: true
        url: '/'
      item2:
        title: 'Link'
        url: '/'
  item4:
    title: 'Disabled'
    url:
      value: '/'
      options:
        attributes:
          class: 'disabled'