title: "Organisms/Offcanvas"
description:
  component: "Offcanvas component description."
## Canvas height
height: 150
## Show button settings:
button_label:
  description: string
  default: 'string'
  table:
    category: fields
## Title settings:
offcanvas_title:
  description: string
  default: 'Offcanvas'
  table:
    category: fields
## Body settings:
offcanvas_body:
  description: string
  default: 'string'
  table:
    category: fields
## Dropdown Items
dropdown:
  items:
    item1:
      title: 'Link'
      url: '/'
    item2:
      title: 'Link'
      url: '/'
    item3:
      title: 'Link'
      url: '/'
    item4:
      title: 'Disabled'
      url:
        value: '/'
        options:
          attributes:
            class: 'disabled'