<?php

/**
 * @file
 * Contains varbase_components.module.
 */

/**
 * Implements hook_theme().
 */
function varbase_components_theme($existing, $type, $theme, $path) {
  return [
    'media_oembed_iframe__remote_video__heroslider' => [
      'template' => 'media-oembed-iframe--remote-video--heroslider',
      'variables' => [
        'provider' => NULL,
        'media' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function varbase_components_preprocess_media_oembed_iframe__remote_video__heroslider(&$variables) {
  // Send variables for the remote_video varbase heroslier oembed iframe.
  $query = \Drupal::request()->query;
  $variables['type'] = $query->get('type');
  $variables['provider'] = $query->get('provider');
  $variables['view_mode'] = $query->get('view_mode');
  $variables['base_path'] = base_path();
  $variables['varbase_components_path'] = \Drupal::service('module_handler')->getModule('varbase_components')->getPath();
}

/**
 * Implements hook_library_info_alter().
 */
function varbase_components_library_info_alter(array &$libraries, $module) {
  if ($module === 'sitewide_alert' && isset($libraries['init'])) {
    // Add the dependency only if it's not already present.
    if (!in_array('core/components.varbase_components--alert', $libraries['init']['dependencies'])) {
      $libraries['init']['dependencies'][] = 'core/components.varbase_components--alert';
    }
    unset($libraries['init']['css']);
  }
}
