<?php

/**
 * @file
 * Install, update and uninstall functions for the Varbase components module.
 */

use Vardot\Installer\ModuleInstallerFactory;

/**
 * Implements hook_install().
 */
function varbase_components_install() {
  // Processor for install: in varbase_components.info.yml file using the Module Installer Factory.
  ModuleInstallerFactory::installList('varbase_components');

  // Add permissions.
  ModuleInstallerFactory::addPermissions('varbase_components');

}
