<?php

/**
 * @file
 * Contains varbase_components.module.
 */

/**
 * Implements hook_theme().
 */
function varbase_components_theme($existing, $type, $theme, $path) {
  return [
    'media_oembed_iframe__remote_video__heroslider' => [
      'template' => 'media-oembed-iframe--remote-video--heroslider',
      'variables' => [
        'provider' => NULL,
        'media' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function varbase_components_preprocess_media_oembed_iframe__remote_video__heroslider(&$variables) {
  // Send variables for the remote_video varbase heroslier oembed iframe.
  $query = \Drupal::request()->query;
  $variables['type'] = $query->get('type');
  $variables['provider'] = $query->get('provider');
  $variables['view_mode'] = $query->get('view_mode');
  $variables['base_path'] = base_path();
  $variables['varbase_components_path'] = \Drupal::service('module_handler')->getModule('varbase_components')->getPath();
}