title: "Organisms/Blocks"
description:
  component: "CTA component description."
## Canvas height
height: 150
## CTA width settings
width:
  description: Bootstrap class
  table:
    category: settings
  default: 'w-50'
  options:
    '25%': 'w-25'
    '50%': 'w-50'
    '75%': 'w-75'
    '100%': 'w-100'
## CTA background color
bg_color:
  description: Bootstrap class
  table:
    category: settings
  default: 'white'
  options:
    'Primary': 'primary'
    'Secondary': 'secondary'
    'Success': 'success'
    'Danger': 'danger'
    'Warning': 'warning'
    'Info': 'info'
    'Dark': 'dark'
    'Light': 'light'
    'White': 'white'
## CTA background color
text_color:
  description: Bootstrap class
  table:
    category: settings
  default: 'dark'
  options:
    'Primary': 'primary'
    'Secondary': 'secondary'
    'Success': 'success'
    'Danger': 'danger'
    'Warning': 'warning'
    'Info': 'info'
    'Dark': 'dark'
    'Light': 'light'
    'White': 'white'
## CTA background color
border_radius:
  description: Bootstrap class
  table:
    category: settings
  default: '0'
  options:
    '0': '0'
    '1': '1'
    '2': '2'
    '3': '3'
    '4': '4'
    '5': '5'
## Title tag settings
title_tag:
  description: 'HTML tag'
  table:
    category: 'settings'
  default: 'h2'
  options:
    'H1': 'h1'
    'H2': 'h2'
    'H3': 'h3'
    'H4': 'h4'
    'H5': 'h5'
    'H6': 'h6'
## Heading settings.
heading:
  description: string
  default: 'string'
  table:
    category: fields
## Content settings.
content:
  description: string
  default: 'string'
  table:
    category: fields