title: "Atoms/Image"
description:
  component: "Image component description."
## Canvas height
height: 150
## Responsive image settings
responsive:
  description: boolean
  default: false
  table:
    category: settings
## alignment settings
align:
  description: Bootstrap class
  table:
    category: settings
  default: 'left'
  options:
    'Left': 'float-start'
    'Center': 'mx-auto d-block'
    'Right': 'float-end'