title: "Organisms/Footer"
description:
  component: "Footer component description"
## Canvas height
height: 150
# Text settings
text:
  description: "string"
  default: "string"
  table:
    category: "fields"
## Nav Items
items:
  item1:
    title: 'Link'
    url: '/'
  item2:
    title: 'Link'
    url: '/'
  item3:
    title: 'Link'
    url: '/'