name: Varbase Components - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - ui_patterns
  - ui_patterns_layouts
  - ui_patterns_library
  - ui_patterns_views
  - ui_patterns_field_formatters
  - ui_patterns_field_group
  - ui_patterns_ds
config:
  import:
    ui_patterns: "*"
    ui_patterns_layouts: "*"
    ui_patterns_library: "*"
    ui_patterns_views: "*"
    ui_patterns_field_formatters: "*"
    ui_patterns_field_group: "*"
    ui_patterns_ds: "*"
