name: Varbase Components - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - ui_patterns_field_group
config:
  import:
    ui_patterns_field_group: '*'
