title: 'Organisms/Blocks'
description:
  component: 'Image block component description.'
## Canvas height
height: 150
## Allow title settings
allow_title:
  description: 'boolean'
  default: false
  table:
    category: 'settings'
## Image block title tag settings
title_tag:
  description: 'string'
  default: 'h2'
  table:
    category: 'settings'
  options:
    'H1': 'h1'
    'H2': 'h2'
    'H3': 'h3'
    'H4': 'h4'
    'H5': 'h5'
    'H6': 'h6'
## Image block title settings
block_title:
  description: 'string'
  default: 'string'
  table:
    category: 'fields'
## Link settings
link:
  description: 'boolean'
  default: false
  table:
    category: 'settings'
## Image block link settings
link_href:
  description: 'string'
  default: 'string'
  table:
    category: 'settings'
## Responsive image settings
responsive:
  description: 'boolean'
  default: false
  table:
    category: 'image settings'
## alignment settings
align:
  description: Bootstrap class
  table:
    category: 'image settings'
  default: 'left'
  options:
    'Left': 'float-start'
    'Center': 'mx-auto d-block'
    'Right': 'float-end'