title: "Organisms/Cards/Overlay Card"
description:
  component: "Overlay card component description."
## Canvas height
height: 250
## Heading html tag settings
heading_tag:
  description: "html tag"
  table:
    category: "settings"
  default: "h2"
  options:
    "H1": "h1"
    "H2": "h2"
    "H3": "h3"
    "H4": "h4"
    "H5": "h5"
    "H6": "h6"
## Horizontal alignment settings
horizontal_alignment:
  description: "Horizontal alignment"
  table:
    category: "settings"
  default: "center"
  options:
    "Left": "start"
    "Center": "center"
    "Right": "end"
## Vertical alignment settings
vertical_alignment:
  description: "Vertical alignment"
  table:
    category: "settings"
  default: "center"
  options:
    "Top": "start"
    "Center": "center"
    "Bottom": "end"
## Heading string settings
heading:
  description: "string"
  default: "string"
  table:
    category: "fields"
## Body string settings
body:
  description: "string"
  default: "string"
  table:
    category: "fields"
## Link string settings
link:
  description: "string"
  default: "string"
  table:
    category: "fields"
