title: "Pages/PageUserRegister"
description:
  component: "Page User Register component description."
## Canvas height
height: 500
## Demo data.
data:
  page_content: |
    <div data-drupal-messages-fallback="" class="hidden"></div>
    <h2 class="block-title"><span> Sign up with </span></h2>
    <section id="block-vartheme-bs5-socialauthlogin" class="settings-tray-editable block block-social-auth block-social-auth-login clearfix" data-drupal-settingstray="editable">
        <div class="social-auth">
          <div class="social-network social_auth_google">
              <a class="auth-link" href="/user/login/google">
              <img class="auth-icon" src="/images/social_auth/social_auth_google/img/google_logo.svg" alt="Authenticate through Google">
              <span class="auth-name">Google</span>
              </a>
          </div>
          <div class="social-network social_auth_facebook">
              <a class="auth-link" href="/user/login/facebook">
              <img class="auth-icon" src="/images/social_auth/social_auth_facebook/img/facebook_logo.svg" alt="Authenticate through Facebook">
              <span class="auth-name">Facebook</span>
              </a>
          </div>
          <div class="social-network social_auth_twitter">
              <a class="auth-link" href="/user/login/twitter">
              <img class="auth-icon" src="/images/social_auth/social_auth_twitter/img/twitter_logo.svg" alt="Authenticate through Twitter">
              <span class="auth-name">Twitter</span>
              </a>
          </div>
          <div class="social-network social_auth_linkedin">
              <a class="auth-link" href="/user/login/linkedin">
              <img class="auth-icon" src="/images/social_auth/social_auth_linkedin/img/linkedin_logo.svg" alt="Authenticate through LinkedIn">
              <span class="auth-name">LinkedIn</span>
              </a>
          </div>
        </div>
    </section>
    <h2 class="block-title"><span> or </span></h2>
    <form class="user-register-form user-form antibot form" data-user-info-from-browser="" data-drupal-selector="user-register-form" autocomplete="off" data-action="/user/register" action="/user/register" method="post" id="user-register-form" accept-charset="UTF-8" data-once="form-updated user-info-from-browser" data-drupal-form-fields="edit-mail,edit-submit,edit-url">
        <noscript>
          <div class="antibot-no-js antibot-message antibot-message-warning">You must have JavaScript enabled to use this form.</div>
        </noscript>
        <div data-drupal-selector="edit-account" id="edit-account" class="js-form-wrapper form-wrapper">
          <div class="js-form-item form-item js-form-type-email form-item-mail js-form-item-mail form-group">
              <label class="form-label js-form-required form-required" for="edit-mail">Email</label>
              <input data-drupal-selector="edit-mail" aria-describedby="edit-mail--description" type="email" id="edit-mail" name="mail" value="" size="60" maxlength="254" class="form-email required form-control" required="required" aria-required="true" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%;">
              <small id="edit-mail--description" class="description form-text text-muted">
              A valid email address. All emails from the system will be sent to this address. The email address is not made public and will only be used if you wish to receive a new password or wish to receive certain news or notifications by email.
              </small>
          </div>
        </div>
        <input autocomplete="off" data-drupal-selector="form-u60zrq2plhrldq5p7la-kmnotx5w2ok5j15meg8ndk8" type="hidden" name="form_build_id" value="form-u60ZRQ2pLhrldq5p7LA_KmNotx5W2ok5J15mEG8ndk8" class="form-control">
        <input data-drupal-selector="edit-user-register-form" type="hidden" name="form_id" value="user_register_form" class="form-control">
        <input data-drupal-selector="edit-antibot-key" type="hidden" name="antibot_key" value="X6oRFwy21ShOxZqmTUo_2KS3LvxqUMg2_7q4925ci0w" class="form-control">
        <input data-drupal-selector="edit-honeypot-time" type="hidden" name="honeypot_time" value="E9ucJ-Qqm_Pabj6IVgyspMINTmsk4sQ6g3ZjTPfvfqU" class="form-control">
        <div data-drupal-selector="edit-actions" class="form-actions js-form-wrapper form-wrapper" id="edit-actions">
          <input data-drupal-selector="edit-submit" type="submit" id="edit-submit" name="op" value="Create new account" class="button--primary js-form-submit form-submit btn btn-primary">
        </div>
        <div class="url-textfield js-form-wrapper form-wrapper" style="display: none !important;">
          <div class="js-form-item form-item js-form-type-textfield form-item-url js-form-item-url form-group">
              <label class="form-label" for="edit-url">Leave this field blank</label>
              <input autocomplete="off" data-drupal-selector="edit-url" type="text" id="edit-url" name="url" value="" size="20" maxlength="128" class="form-textfield form-control">
          </div>
        </div>
    </form>
  footer_content: |
    <div class="footer-top d-flex justify-content-md-between align-items-md-center">
      <div>Powered by <a href="https://www.vardot.com/?utm_source=varbase&amp;utm_campaign=varbase%20default%20links">Vardot</a>. Enjoy the free software, or <a href="https://www.vardot.com/form/get-support-varbase?utm_source=varbase&amp;utm_campaign=varbase%20default%20links">get a quote</a> for enterprise support and fully functional websites.</div>
      <ul class="nav">
          <li class="nav-item  ">
            <a href="https://www.drupal.org/project/issues/varbase" class="nav-link" target="_blank" rel="noopener">Community Support</a>
          </li>
          <li class="nav-item  ">
            <a href="https://docs.varbase.vardot.com/?utm_source=varbase&amp;utm_campaign=varbase%20default%20links" class="nav-link">Documentation</a>
          </li>
          <li class="nav-item  ">
            <a href="https://www.vardot.com/form/get-support-varbase?utm_source=varbase&amp;utm_campaign=varbase%20default%20links" class="nav-link">Get Professional Support</a>
          </li>
      </ul>
    </div>